language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
#script:
#- python petitioner/manage.py test
before_install:

- openssl aes-256-cbc -K $encrypted_5cbbea8aa25b_key -iv $encrypted_5cbbea8aa25b_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d

- tar -xzf credentials.tar.gz
- mkdir -p lib
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file petition-16af568bdafa.json
# [END auth]
install:
# Set the correct project to deploy to
- gcloud config set project petition-144421
- gcloud -q components update gae-python
# Install the Python dependencies
- pip install -r requirements.txt

script:
# Run the unit tests
- python petitioner/manage.py test
# [START deploy]
# Deploy the app
- gcloud -q preview app deploy app.yaml --promote